name: Build and Test

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]
    types: [ opened, synchronize, reopened ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings -Cdebuginfo=1
  RUSTDOCFLAGS: --deny warnings

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - name: Build
        run: cargo build

      - name: Format
        run: cargo fmt --all -- --check

      - name: Lint
        run: cargo clippy --workspace --all-targets --all-features --locked

      - name: Test
        run: cargo test --verbose
